start: element+

element: equation
     | note
     | block
     | block_math
     | TEXT
     | new_line

equation: "$" TEXT "$"
block_math: "$$" TEXT+ "$$"

note: "\\begin{note}{" TEXT "}" content_note+ "\\end{note}"
content_note: (equation | TEXT | new_line)*

block: "\\begin{block}" item+ "\\end{block}"
item: "\\begin{item}" (TEXT | equation | custom_note | new_line)+ "\\end{item}"

new_line: "@" "newline"

TEXT: /[^<>{}$@|]+/

%import common.WS
%ignore WS

IDENTIFIER: /[a-zA-Z][a-zA-Z0-9]*/
